RealEstate/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('properties/', include('properties.urls', namespace='properties')),
    path('about/', include('about.urls', namespace='about')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('', include('home.urls', namespace='home')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),

]

properties/urls.py
from django.urls import path
from .views import property_list, property_detail, property_neighbors

app_name = 'properties'

urlpatterns = [
    path('', property_list, name='property_list'),
    path('<int:id>', property_detail, name='property_detail'),
    path('neighbors/', property_neighbors, name='property_neighbors'),
    path('neighbors/<int:id>', property_neighbors, name='property_neighbors'),
]

properties/models.py
from django.db import models
import secrets


def ads_keys():
    ads_key = secrets.token_hex()
    ads_key = str.upper(ads_key)
    ads_key = ads_key[0:8]
    print(ads_key)
    return ads_key


pr_type = (
    ('Sale', "Sale"),
    ('Rent', "Rent"),
)

pr_featured = (
    ('Yes', "Yes"),
    ('No', "No"),
)

class Property(models.Model):
    name = models.CharField(max_length=150)
    location = models.CharField(max_length=50, null=True, default="null")
    state = models.ForeignKey('States', null=True, on_delete=models.SET_NULL)
    type = models.CharField(choices=pr_type, max_length=50)
    price = models.PositiveIntegerField()
    area = models.PositiveIntegerField()
    beds = models.PositiveIntegerField()
    baths = models.PositiveIntegerField()
    garages = models.PositiveIntegerField()
    image = models.ImageField(upload_to='property_images/', default='property_images/default.png')
    ads_id = models.CharField(max_length=8, default=ads_keys, editable=True)
    featured = models.CharField(choices=pr_featured, max_length=50, default="No")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Property"
        verbose_name_plural = "Properties"


class States(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='state_images/', default='state_images/default.png')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "State"
        verbose_name_plural = "States"


class Reserve(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    notes = models.TextField()
    ads_id = models.CharField(max_length=8)

    def __str__(self):
        return self.first_name

properties/forms.py
from django import forms
from .models import Reserve


class ReserveForm(forms.ModelForm):
    class Meta:
        model = Reserve
        fields = '__all__'

properties/views.py
from django.shortcuts import render
from django.db.models import Q
from django.db.models import Count
from .models import Property, States
from .forms import ReserveForm


def property_list(request):

    property_list = Property.objects.all()
    state_list = States.objects.annotate(property_count=Count('property')).values('name', 'property_count', 'image',
                                                                                  'id')
    #state_list = States.objects.all()
    template = 'properties/list.html'

    address_query = request.POST.get('q')
    print(address_query)
    property_type = request.POST.getlist('property_type', None)
    print(property_type)
    if address_query and property_type:
        property_list = property_list.filter(
            Q(name__icontains=address_query) &
            Q(type__icontains=property_type[0])
        ).distinct()

    context = {
        'property_list': property_list,
        'state_list': state_list,
    }
    return render(request, template, context)


def property_detail(request, id):
    property_detail = Property.objects.get(id=id)
    template = 'properties/detail.html'

    if request.method == 'POST':
        reserve_form = ReserveForm(request.POST)
        if reserve_form.is_valid():
            instance = reserve_form.save(commit=False)
            instance.ads_id = property_detail.ads_id
            print(instance.ads_id)
            instance.save()
    else:
        reserve_form = ReserveForm()

    context = {
        'property_detail': property_detail,
        'reserve_form': reserve_form
    }

    return render(request, template, context)


def property_neighbors(request, id):
    property_neighbors = Property.objects.all().filter(state=id)
    #state_list = States.objects.all()
    state_list = States.objects.annotate(property_count=Count('property')).values('name', 'property_count', 'image',
                                                                                  'id')
    template = 'properties/list_neighbors.html'
    context = {
        'property_neighbors': property_neighbors,
        'state_list': state_list
    }

    return render(request, template, context)

templates/properties/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                  <a href="#">Home</a><span><a href="{% url 'properties:property_list' %}">Properties</a></span>{{ property_detail }}
              </div>
              <h1>{{ property_detail }}</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(../../static/img/slider_1.jpg);"></li>
      <li style="background-image: url(../../static/img/slider_4.jpg);"></li>
      <li style="background-image: url(../../static/img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p><img src="{{property_detail.image.url}}" class="img-responsive" alt="Free Bootstrap Template by uicookies.com"></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h2>Details</h2>
          <p>Rent/Sale: {{ property_detail.type }}</p>
          <p>Price: {{ property_detail.price }} USD</p>
            <p>GPS Location: {{ property_detail.location }}</p>
          <p>City: {{ property_detail.state }}</p>
          <p>Area: {{ property_detail.area }} m2</p>
          <p>Beds: {{ property_detail.beds }}</p>
          <p>Baths: {{ property_detail.baths }}</p>
          <p>Garages: {{ property_detail.garages }}</p>
          <strong><p>Property_ID: {{ property_detail.ads_id }}</p></strong>
        </div>
      </div>
    </div>
  </section>
  <section class="probootstrap-section">
    <div class="container">

      <div class="row">
        <div class="col-md-12">
          <h2>Reserve This Property</h2>
            <form action="" method="POST">
                {% csrf_token %}
                {% bootstrap_field reserve_form.first_name %}
                {% bootstrap_field reserve_form.last_name %}
                {% bootstrap_field reserve_form.email %}
                {% bootstrap_field reserve_form.notes %}
                <input type="hidden", value="12345678", name="ads_id">
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Reserve</button>
                {% endbuttons %}
            </form>

        </div>
      </div>
    </div>
  </section>

{% endblock %}

templates/properties/list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  <div class="probootstrap-loader"></div>
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span>Properties</span>
              </div>
              <h1>Properties</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url({% static 'img/slider_1.jpg' %});"></li>
      <li style="background-image: url({% static 'img/slider_4.jpg' %});"></li>
      <li style="background-image: url({% static 'img/slider_2.jpg' %});"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row">
          {% for property in property_list %}
            <div class="col-md-4 col-sm-6">
          <div class="probootstrap-card probootstrap-listing">
            <div class="probootstrap-card-media">
              <img src="{{property.image.url}}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
              <a href="#" class="probootstrap-love"><i class="icon-heart"></i></a>
            </div>
            <div class="probootstrap-card-text">
                <h2 class="probootstrap-card-heading"><a href="{% url 'properties:property_detail' property.id %}">{{property}}</a></h2>
                <div class="probootstrap-listing-location">
                    <i class="icon-location2"></i> <span>{{property.location}} / <a href="{% url 'properties:property_neighbors' property.state_id %}">{{property.state}}</a></span>
                </div>
                {% ifequal property.type 'Sale' %}
                    <div class="probootstrap-listing-category for-sale"><span>{{property.type}}</span></div>
                    <div class="probootstrap-listing-price"><strong>$ {{property.price}}</strong></div>
                {% endifequal %}
                {% ifequal property.type 'Rent' %}
                    <div class="probootstrap-listing-category for-rent"><span>{{ property.type }}</span></div>
                    <div class="probootstrap-listing-price"><strong>{{ property.price }}</strong> / month</div>
                {% endifequal %}
            </div>
            <div class="probootstrap-card-extra">
              <ul>
                <li>
                  Area
                  <span>{{property.area}} m2</span>
                </li>
                <li>
                  Beds
                  <span>{{ property.beds }}</span>
                </li>
                <li>
                  Baths
                  <span>{{ property.baths }}</span>
                </li>
                <li>
                  Garages
                  <span>{{ property.garages }}</span>
                </li>
              </ul>
            </div>
          </div>
          <!-- END listing -->
        </div>
          {% endfor %}
      </div>
    </div>
  </section>
    <section class="probootstrap-section">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">Explore Our Neighborhoods</h2>
      </div>
      <div class="row probootstrap-gutter10">
        {% for state in state_list %}
           <div class="col-md-6 col-sm-6">
                <a href="{% url 'properties:property_neighbors' state.id %}" class="probootstrap-hover-overlay">
                    <div class="probootstrap-card-media">
                    <img src="/media/{{ state.image }}" alt="Free Bootstrap Template by uicookies.com" class="img-responsive">
                    </div>
                <div class="probootstrap-text-overlay">
                    <h3>{{state.name}}</h3>
                    <p>{{state.property_count}}</p>
                </div>
                </a>
            </div>
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock %}

templates/properties/list_neighbors.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  <div class="probootstrap-loader"></div>
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span>Properties</span>
              </div>
              <h1>Properties</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url({% static 'img/slider_1.jpg' %});"></li>
      <li style="background-image: url({% static 'img/slider_4.jpg' %});"></li>
      <li style="background-image: url({% static 'img/slider_2.jpg' %});"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row">
          {% for property in property_neighbors %}
            <div class="col-md-4 col-sm-6">
          <div class="probootstrap-card probootstrap-listing">
            <div class="probootstrap-card-media">
              <img src="{{property.image.url}}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
              <a href="#" class="probootstrap-love"><i class="icon-heart"></i></a>
            </div>
            <div class="probootstrap-card-text">
                <h2 class="probootstrap-card-heading"><a href="{% url 'properties:property_detail' property.id %}">{{property}}</a></h2>
                <div class="probootstrap-listing-location">
                    <i class="icon-location2"></i> <span>{{property.location}} / <a href="{% url 'properties:property_neighbors' property.state_id %}">{{property.state}}</a></span>
              </div>
                {% ifequal property.type 'Sale' %}
                    <div class="probootstrap-listing-category for-sale"><span>{{property.type}}</span></div>
                    <div class="probootstrap-listing-price"><strong>$ {{property.price}}</strong></div>
                {% endifequal %}
                {% ifequal property.type 'Rent' %}
                    <div class="probootstrap-listing-category for-rent"><span>{{ property.type }}</span></div>
                    <div class="probootstrap-listing-price"><strong>{{ property.price }}</strong> / month</div>
                {% endifequal %}
            </div>
            <div class="probootstrap-card-extra">
              <ul>
                <li>
                  Area
                  <span>{{property.area}} m2</span>
                </li>
                <li>
                  Beds
                  <span>{{ property.beds }}</span>
                </li>
                <li>
                  Baths
                  <span>{{ property.baths }}</span>
                </li>
                <li>
                  Garages
                  <span>{{ property.garages }}</span>
                </li>
              </ul>
            </div>
          </div>
          <!-- END listing -->
        </div>
          {% endfor %}
      </div>
    </div>
  </section>

  <section class="probootstrap-section">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">Explore Our Neighborhoods</h2>
      </div>
      <div class="row probootstrap-gutter10">
        {% for state in state_list %}
           <div class="col-md-6 col-sm-6">
                <a href="{% url 'properties:property_neighbors' state.id %}" class="probootstrap-hover-overlay">
                    <div class="probootstrap-card-media">
                    <img src="/media/{{ state.image }}" alt="Free Bootstrap Template by uicookies.com" class="img-responsive">
                    </div>
                <div class="probootstrap-text-overlay">
                    <h3>{{state.name}}</h3>
                    <p>{{state.property_count}}</p>
                </div>
                </a>
            </div>
        {% endfor %}
      </div>
    </div>
  </section>
  <!-- END: section -->
{% endblock %}